# Generated by Django 4.2.4 on 2023-08-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
    ]
