# Generated by Django 4.2.4 on 2023-08-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_comment_author_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Прошёл активацию?'),
        ),
    ]
